//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Docente.java
//  @ Date : 15/11/2021
//  @ Author : 
//
//

public class Docente extends Persona {
	private String materia;

	public Docente(String myNome, String myCognome, String myMateria)
	{
		super(myNome,myCognome);
		this.materia=myMateria;
	}

	@Override
	void presentati()
	{
		System.out.println("\nSono dentro presentati() come docente\nSono un docente");
		super.presentati();
		System.out.println("Insegno: "+this.materia+"\nEsco da presentati()");
	}

}
