//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Persona.java
//  @ Date : 15/11/2021
//  @ Author : 
//
//




public class Persona {
	private String cognome;
	private String nome;
	
	public Persona(String myNome, String myCognome)
	{
		this.nome=myNome;
		this.cognome=myCognome;
	}

	void presentati()
	{
		System.out.println("Sono una persona");
		System.out.println("Il mio nome e': "+this.nome);
		System.out.println("Il mio cognome e': "+this.cognome);
	}
}
