//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StudenteFuoriSede.java
//  @ Date : 15/11/2021
//  @ Author : 
//
//

public class StudenteFuoriSede extends Studente {
	private String residenza;

	public StudenteFuoriSede (String myNome, String myCognome, String myStudi, String myResidenza)
	{
		super(myNome,myCognome,myStudi);
		this.residenza=myResidenza;
	}

	@Override
	void presentati()
	{
		System.out.println("\nSono dentro presentati() come studente fuori sede\nSono uno studente fuori sede");
		super.presentati();
		System.out.println("Risiedo a: "+this.residenza+"\nEsco da presentati()");
	}

}
