//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Studente.java
//  @ Date : 15/11/2021
//  @ Author : 
//
//




public class Studente extends Persona {
	private String studi;
	
	public Studente(String myNome, String myCognome, String myStudi)
	{
		super(myNome,myCognome);
		this.studi=myStudi;
	}

	@Override
	void presentati()
	{
		System.out.println("\nSono dentro presentati() come studente\nSono uno studente");
		super.presentati();
		System.out.println("Studio: "+this.studi+"\nEsco da presentati()");
	}
}
